/* Generated by Yosys 0.27+22 (git sha1 53c0a6b78, clang 14.0.0 -fPIC -Os) */

(* cells_not_processed =  1  *)
(* src = "../verilog_workspace/dec3x8_pre_synth_2x.v:9.1-27.10" *)
module dec3x8_pre_synth_2x(A0, A1, A2, EN, O);
  wire _00_;
  wire _01_;
  wire _02_;
  (* src = "../verilog_workspace/dec3x8_pre_synth_2x.v:10.11-10.13" *)
  input A0;
  wire A0;
  (* src = "../verilog_workspace/dec3x8_pre_synth_2x.v:10.15-10.17" *)
  input A1;
  wire A1;
  (* src = "../verilog_workspace/dec3x8_pre_synth_2x.v:10.19-10.21" *)
  input A2;
  wire A2;
  (* src = "../verilog_workspace/dec3x8_pre_synth_2x.v:10.23-10.25" *)
  input EN;
  wire EN;
  (* src = "../verilog_workspace/dec3x8_pre_synth_2x.v:11.23-11.24" *)
  output [7:0] O;
  wire [7:0] O;
  inv_2x _03_ (
    .I(A2),
    .O(_00_)
  );
  inv_2x _04_ (
    .I(A0),
    .O(_01_)
  );
  inv_2x _05_ (
    .I(A1),
    .O(_02_)
  );
  and4_2x _06_ (
    .A(EN),
    .B(_00_),
    .C(_01_),
    .D(_02_),
    .O(O[0])
  );
  and4_2x _07_ (
    .A(EN),
    .B(_00_),
    .C(A0),
    .D(_02_),
    .O(O[1])
  );
  and4_2x _08_ (
    .A(EN),
    .B(_00_),
    .C(_01_),
    .D(A1),
    .O(O[2])
  );
  and4_2x _09_ (
    .A(EN),
    .B(_00_),
    .C(A0),
    .D(A1),
    .O(O[3])
  );
  and4_2x _10_ (
    .A(EN),
    .B(A2),
    .C(_01_),
    .D(_02_),
    .O(O[4])
  );
  and4_2x _11_ (
    .A(EN),
    .B(A2),
    .C(A0),
    .D(_02_),
    .O(O[5])
  );
  and4_2x _12_ (
    .A(EN),
    .B(A2),
    .C(_01_),
    .D(A1),
    .O(O[6])
  );
  and4_2x _13_ (
    .A(EN),
    .B(A2),
    .C(A0),
    .D(A1),
    .O(O[7])
  );
endmodule
